Create RadioGroup Component
Trova-Trip/trova-components pull request #101
Opened 2021-06-17 22:38 UTC by cristian-seoane

Added a new RadioGroup component based on MaterialUI 's RadioGroup component

2021-06-18 07:24 UTC, BrandonDenham requested changes

2021-06-18 07:24 UTC, BrandonDenham commented on src/components/RadioGroup/_private/radio.tsx
> +                    id={name}
do we need the id?

2021-06-18 07:24 UTC, BrandonDenham commented on src/components/RadioGroup/radioGroup.test.tsx
> +
too much space, wouldn't prettier remove this?

2021-06-18 07:24 UTC, BrandonDenham commented on src/components/RadioGroup/radioGroup.tsx
> +                        <Fragment key={`${value}Input${index}`}>
Fragment is unnecessary

2021-06-18 07:24 UTC, BrandonDenham commented on src/components/RadioGroup/radioGroup.tsx
> +                    {children.map(({ value, children }, index) => (
may want to use React.children since it's possible that children is a single element?

2021-06-18 07:24 UTC, BrandonDenham commented on src/components/RadioGroup/radioGroup.test.tsx
> +            children: [
oh this is not what this is supposed to look like:

the children should be react Elements Options:
```
<RadioGroup>
    <Option value={value}>{label}</Option>
</RadioGroup>
```


This is how material ui does options

2021-06-18 07:24 UTC, BrandonDenham commented on src/components/RadioGroup/radioGroup.test.tsx
> +            children: [
I know the select component does't behave this way, but it should.  That was a bad implementation that we shouldnt copy here.  

I would rather we update the select to do it this way.  

what the RadioGroup should do is export a context that is consumed by the Options, so that when an "Option" is selected it sets the value on the field.

2021-06-18 07:24 UTC, BrandonDenham commented on src/modules/HtmlInputProps.d.ts
> +import {} from 'react';
why woud we need to declare this? there is already a react module.

2021-06-18 13:55 UTC, cristian-seoane commented on src/components/RadioGroup/radioGroup.test.tsx
> +            children: [
Absolutely agree, I'll create a  Option component.

2021-06-18 13:56 UTC, cristian-seoane commented on src/components/RadioGroup/radioGroup.tsx
> +                        <Fragment key={`${value}Input${index}`}>
Got it!

2021-06-18 13:56 UTC, cristian-seoane commented on src/components/RadioGroup/radioGroup.test.tsx
> +
oh, yes I deleted something there just before to commit the changes, and forgot re-run prettier, my bad, already fixed.

2021-06-18 13:56 UTC, cristian-seoane commented on src/components/RadioGroup/_private/radio.tsx
> +                    id={name}
yeap, the prop " htmlFor "   from <label/>  allows the label to be a button for that id input, otherwise the label would just be plain text

2021-06-18 14:06 UTC, cristian-seoane commented on src/modules/HtmlInputProps.d.ts
> +import {} from 'react';
yeap that declaration resolves the warning: " data-testid'' does not exist in type 'InputHTMLAttributes<HTMLInputElement>' "

2021-06-22 13:22 UTC, cristian-seoane commented on src/components/RadioGroup/radioGroup.tsx
> +                    {children.map(({ value, children }, index) => (
got it!

2021-06-22 22:21 UTC, BrandonDenham approved these changes

2021-06-22 22:21 UTC, BrandonDenham commented on src/components/RadioGroup/radioGroup.tsx
> +                    {Array.isArray(children) ? (
i dont think you need Array.isArray when you use React.Childrent

2021-06-22 22:21 UTC, BrandonDenham commented on src/components/RadioGroup/radioGroup.tsx
> +                    {Array.isArray(children) ? (
the React.Children can handle the non Array case so you don't need the condition or the second halve of the ternary.

2021-06-24 18:06 UTC, cristian-seoane commented on src/components/RadioGroup/radioGroup.tsx
> +                    {Array.isArray(children) ? (
I agree, but it is necessary to resolve  the 'prop'   type warning

2021-06-24 18:07 UTC, merged