Saga 2.98/responsive main navigation components
Trova-Trip/trova-components pull request #122
Opened 2021-08-12 23:55 UTC by juligobbi-fluxit

New mobile styles for the Sidebar/MainNavigation after the changes that have been implemented to handle dynamic display on the sidebar.

- Fixing the second vertical scroll on the sidebar when is expanded
- Fixing the layer height for the first level of navigation (trips and itineraries). Making it full screen.
- Styling and spacing the inner menu from desktop to mobile devices
- Adding the style for the arrow icon to collapse and expand the menu

This is a branch built together with maven's branch: saga-2.98/responsive-main-navigation
In Asana: https://asanal.ink/21/98

2021-08-13 05:25 UTC, BrandonDenham requested changes

2021-08-13 05:25 UTC, BrandonDenham commented on src/components/sidebar/SidebarMenu.tsx
> +                )}
so i wouldn't completely replace the component the way that you are with the boolean, rather, you should replace the variables above, something like this:

```
const altText = openMenu ? 'Open' : 'Close';
const sidebarCss = openMenu ? sidebarMenuOpenImage : sidebarMenuCloseImage;
```

then this part would change to:

```suggestion
                  <img
                      alt={altText}
                      src={imgArrow}
                      css={sidebarCss}
                      onClick={toggle}
                  />
             
```

2021-08-13 14:49 UTC, juligobbi-fluxit commented on src/components/sidebar/SidebarMenu.tsx
> +                )}
love it! too much better! :) thanks for sharing it. I will commit that

2021-08-17 16:33 UTC, BrandonDenham approved these changes

2021-08-17 17:01 UTC, merged