saga-4.295: Adding a new bottom variant of Modal for mobile screens
Trova-Trip/trova-components pull request #133
Opened 2021-09-09 02:55 UTC by juligobbi-fluxit

In Asana: https://app.asana.com/0/1200871770472728/1200891873931394/f

Creating a new bottom position variant of Modal for mobile screens.

- Adding position props: 
    -centered (as default)
    -bottom
- New layout for scrolling, with a container for header and body modal
- New layout header inner which contains title, subtitle, and close button*

Note:
*It would be nice to refactor the default layout with this header implementation.

2021-09-09 05:23 UTC, BrandonDenham requested changes

2021-09-09 05:23 UTC, BrandonDenham commented on src/components/Dialog/_private/dialogContent.tsx
> +            <Fragment>
most of this code is duplicated in either position.  This shouldn't be done this way, it looks like position barely affects the difference in either implementation.  don't know what we need the position == centered or position == bottom

also, we always use strict equality ===

2021-09-09 15:46 UTC, juligobbi-fluxit commented on src/components/Dialog/_private/dialogContent.tsx
> +            <Fragment>
I was thinking..Maybe I could do 2 different things to solve this:

1. position centered and bottom with just an if on the main container. I need different styles for both of them at this high level, so I need to differentiate them

2. make a refactoring for Dialog, implementing a wrapper for header and a wrapper for body (as I did on the bottom layout), and even I could add a wrapper for footer (to separate the buttons)

2021-09-17 06:06 UTC, rmcarias requested changes

2021-09-17 06:06 UTC, rmcarias commented on src/components/Dialog/_private/dialogContent.tsx
> +            <Fragment>
BTW, good tip to know shortcut for Fragment in React is
```
<></>
```

2021-09-21 17:14 UTC, rmcarias commented
@juligobbi-fluxit  is this ready for review again?
CC: @jmoyers14

2021-09-21 23:33 UTC, rmcarias approved these changes
just a minor comment on the position prop

2021-09-21 23:33 UTC, rmcarias commented on src/components/Dialog/_private/dialogContent.types.ts
> +    position?: string;
one thing you can do here to help TS infer the type better is constrain it
position?: 'centered' | 'bottom' | undefined

2021-09-22 00:31 UTC, juligobbi-fluxit commented on src/components/Dialog/_private/dialogContent.types.ts
> +    position?: string;
Great! I love those improvements

2021-09-22 00:52 UTC, rmcarias approved these changes

2021-09-22 06:11 UTC, BrandonDenham approved these changes

2021-09-22 12:28 UTC, merged