saga-8.632: Create IconActionBox component
Trova-Trip/trova-components pull request #149
Opened 2021-11-09 13:54 UTC by cristian-seoane

-Create IconActionBox component
-Add Link icon 
-Change the button children as optional

Spec: https://trovatrip.slite.com/app/channels/bbcRB2YFY8/notes/m5~J7d0Bc

Blocking: https://asanal.ink/21/549

2021-11-09 14:04 UTC, cristian-seoane commented on src/components/button/button.tsx
> +                    {children && (
Just change children as optional the rest is formatting.

2021-11-09 17:50 UTC, BrandonDenham requested changes

2021-11-09 17:50 UTC, BrandonDenham commented on src/components/IconActionBox/IconActionBox.test.tsx
> +expect.extend(matchers);
hmm, can we do this globally somewhere when test scripts are spinning up, then we don't need to do this everytime we write a test

2021-11-09 17:50 UTC, BrandonDenham commented on src/components/IconActionBox/IconActionBox.tsx
> +}
should move to its own types file

RightAddOn is not a good name for this, as we will quickly want a LeftAddOn that is the same interface.

2021-11-09 17:50 UTC, BrandonDenham commented on src/components/IconActionBox/IconActionBox.tsx
> +    rightAddOn,
maybe rightIcon for the prop name?

2021-11-10 21:04 UTC, cristian-seoane commented on src/components/IconActionBox/IconActionBox.test.tsx
> +expect.extend(matchers);
done

2021-11-10 21:04 UTC, cristian-seoane commented on src/components/IconActionBox/IconActionBox.tsx
> +    rightAddOn,
done

2021-11-10 21:04 UTC, cristian-seoane commented on src/components/IconActionBox/IconActionBox.tsx
> +}
done

2021-11-11 08:51 UTC, BrandonDenham commented on src/components/IconActionBox/IconActionBox.tsx
> +    iconButton,
I think this would be better named iconButtonProps.  (same with the interface).

2021-11-11 08:52 UTC, BrandonDenham approved these changes
minor comment, no need for more review

2021-11-11 12:43 UTC, cristian-seoane commented on src/components/IconActionBox/IconActionBox.tsx
> +    iconButton,
done!

2021-11-11 12:43 UTC, merged