saga-8.672/fix-dropdown-styles
Trova-Trip/trova-components pull request #150
Opened 2021-11-09 15:13 UTC by matiasmarquez

Added improvements to the design of the dropdown component. You can see some screenshots of the before/after on Asana.

2021-11-09 15:18 UTC, eringuelet commented
Maybe a good idea will be to move the default radius to a constant so we don't have that value sparsed all over the code...

2021-11-09 15:24 UTC, matiasmarquez commented
> Maybe a good idea will be to move the default radius to a constant so we don't have that value sparsed all over the code...

That's true I just made a magic number instead of a magic string. I will move that value to a constant.

2021-11-09 17:32 UTC, BrandonDenham requested changes

2021-11-09 17:32 UTC, BrandonDenham commented on src/components/dropdown/dropdown.types.ts
> +    radius?: number;
HMM is the radius configurable?  This seems very flexible and i'm not sure we want this with our style guides, @juligobbi-fluxit do we really wan't different options for flexibility with various dropdowns?

2021-11-09 18:10 UTC, matiasmarquez commented on src/components/dropdown/dropdown.types.ts
> +    radius?: number;
Maybe too much flexibility is bad, sorry. Confirm and I will rollback that.

2021-11-10 00:16 UTC, rmcarias requested changes

2021-11-10 00:16 UTC, rmcarias commented on src/components/dropdown/dropdown.types.ts
> +    radius?: number;
I agree with @BrandonDenham - I think we should stick to a set border-radius for the options dropdown and later on if we change our minds, we can update easily and not have a concern they were configured on Maven differently by a Dev.
Also, @matiasmarquez  ask @juligobbi-fluxit  to show you how to create a storybook item for these changes. Would be neat to see examples of this.

2021-11-10 12:43 UTC, matiasmarquez commented on src/components/dropdown/dropdown.types.ts
> +    radius?: number;
I already removed the prop to configure the border-radius. @rmcarias all the changes that I've done on this PR will automatically show on Storybook and it will apply to all the stories of the Dropdown. There is no need to make a new item. I leave you an example: 

![image](https://user-images.githubusercontent.com/31554111/141114992-69a12e93-463b-4d35-9bd3-4f5edda2c8a9.png)

2021-11-10 12:45 UTC, juligobbi-fluxit commented on src/components/dropdown/dropdown.types.ts
> +    radius?: number;
@BrandonDenham @rmcarias We talked with Mati. I agree that the radius should not be configurable. Regarding the stories to reflect these styles, it would not be necessary to add new ones, the changes added are reflected on all the dropdown stories. Is a common style between them.

2021-11-10 20:12 UTC, rmcarias approved these changes

2021-11-10 20:12 UTC, merged