Saga 8.582/floating action tile
Trova-Trip/trova-components pull request #152
Opened 2021-11-10 19:21 UTC by Brendan-Bormann

This PR doesn't contain mobile responsive functionality

2021-11-10 20:17 UTC, rmcarias commented
@BrandonDenham  you take this over please. I know there is probably some discussion on this

2021-11-11 19:38 UTC, BrandonDenham commented on src/components/FloatingTileWrapper/FloatingTileWrapper.tsx
> +    offsetBottom = 0,
Do we have use cases for these 3 props yet?

2021-11-11 19:38 UTC, BrandonDenham commented on src/components/FloatingTileWrapper/FloatingTileWrapper.tsx
> +    floatingTile,
i think maybe calling this floatingTileContent actually makes it clearer,

2021-11-17 23:24 UTC, Brendan-Bormann commented on src/components/FloatingTileWrapper/FloatingTileWrapper.tsx
> +    offsetBottom = 0,
`offsetTop` & `offsetBottom` are both coming from the `StickyBox` component. We are using the `offsetTop` but not `reversed` or `offsetBottom`. They are all optional params too.

2021-11-18 07:44 UTC, BrandonDenham requested changes

2021-11-18 07:44 UTC, BrandonDenham commented on src/components/FloatingTileWrapper/FloatingTileWrapper.tsx
> +    mobileTileContent,
Ok, this isn't what we talked about, but I honestly can feel the pain of the content component that needs to be aware of both. 

In general I don't like "mobile" in the name, it's describing the device when really it's just about the width of the screen.  

Still wondering what @rmcarias thinks of the 2 props, but i think something like 

"anchoredTileContent" or minifiedTileContent is a better name than mobile

2021-11-18 07:44 UTC, BrandonDenham commented on src/components/FloatingTileWrapper/FloatingTileWrapper.styles.tsx
> +        display: none;
i don't love display: none solutions as they leave unnecessary HTML on the page rather than removing it completely.  

It's especially bad in cases like this where the hidden HTML is very unlikely to ever be displayed.  So it's mostly just wasted bits.  

I think there are <Grid> solutions that will just not put the content on the page at all and you don't need to use CSS to hide or show things.

2021-11-18 20:20 UTC, rmcarias approved these changes

2021-11-18 20:32 UTC, jmoyers14 approved these changes

2021-11-18 20:44 UTC, merged