saga-8.613: added mobile footer flag and fixed z-index bug
Trova-Trip/trova-components pull request #170
Opened 2021-11-24 22:35 UTC by Brendan-Bormann

2021-11-25 08:01 UTC, BrandonDenham requested changes

2021-11-25 08:01 UTC, BrandonDenham commented on src/components/FloatingTileWrapper/FloatingTileWrapper.tsx
> +    displayFooter = false,
why is this an option? is there a use case where we don't want to display the footer?  It definitely shouldn't be the default

2021-11-29 17:57 UTC, Brendan-Bormann commented on src/components/FloatingTileWrapper/FloatingTileWrapper.tsx
> +    displayFooter = false,
my intention is to hide it unless:
- there is a mobile design
- the content is built to adjust to mobile

i thought it would be nice since I'm designing something that doesn't have a mobile design yet

2021-11-29 18:00 UTC, BrandonDenham commented on src/components/FloatingTileWrapper/FloatingTileWrapper.tsx
> +    displayFooter = false,
that's just an incomplete design . . . we always need to have a mobile design

2021-11-29 18:36 UTC, rmcarias approved these changes

2021-11-29 18:39 UTC, BrandonDenham approved these changes

2021-11-29 18:39 UTC, merged