Saga 9.240  - Form Saver 2 Initial Commit
Trova-Trip/trova-components pull request #171
Opened 2021-11-29 18:31 UTC by rmcarias

Hi guys, 

This is the initial implementation for our next gen Form Saver - https://trovatrip.slite.com/api/s/note/1AQN5cLYGf1zVe6T6epRmZ/Form-Saver-2

In this version, we have support for the following:

- Hook based
- Yup schema based validation (this will need more examples and docs WIP)
- Field level validation (onChange)
- Form level validation
- Nested Props ( maxed at 3 including root - story example needed)
- Dirty checking (story example needed)
- Reset (story example needed)
- OnSubmit
- OnReset
- Form Wrapper component
- - wraps the basic <form>
- Field Error component
- - display field error

Attention was giving to maintain as much parity with current Form Saver as needed. 
WIP:

- Array types

- Boolean types
- Validation schemas need to be defined in Core (storybook it)
- Example of Server side validation
- Maybe adjust some of the types (TS is being finicky about some TC types)
- Add Yup helper methods (such as initial value)

2021-11-29 23:25 UTC, BrandonDenham requested changes
pretty excited to use this, its looking good.  One comment that i'm hopeful will make the getter's slightly better, but i'm not exactly sure how i'd implement with the proxies, hopefully it's not too difficult

2021-11-29 23:25 UTC, BrandonDenham commented on src/components/FormSaver/FormSaver.types.ts
> +    errors: { [key: string]: string[] } | null;
we should have pageErrors here as well correct?

2021-11-29 23:25 UTC, BrandonDenham commented on src/components/FormSaver/FormSaver.stories.tsx
> +                                        formSaver.formValues.get
rather than casting we could optionally let the client define the type with a generic https://www.typescriptlang.org/docs/handbook/2/generics.html

then the client could just be like:
```
interface User {
    firstName: string,
    lastName: string,
}
```
and if the user called the use function with the type, they wouldn't need to cast:
```
useFormSaver<User>({...});
```
because you could update the Type to whatever the type the user passed.  You can also default the type to any so that this exact same code still works.

2021-11-29 23:50 UTC, BrandonDenham approved these changes

2021-11-30 01:08 UTC, rmcarias commented on src/components/FormSaver/FormSaver.types.ts
> +    errors: { [key: string]: string[] } | null;
yup...will make that change now

2021-11-30 01:29 UTC, merged