saga-10.885/feature-form-saver-types
Trova-Trip/trova-components pull request #190
Opened 2021-12-17 11:53 UTC by matiasmarquez

Added support to form saver types to allow multiple dropdowns

2021-12-17 16:47 UTC, rmcarias requested changes

2021-12-17 16:47 UTC, rmcarias commented on src/components/FormSaver/FormSaver.types.ts
> +export type SetterFuncPath = (path: string | string[] | React.SyntheticEvent, value?: any) => void;
I am not sure this is correct. Path is really meant for two use-cases:
direct assignment to an HTML event and as path sent to lodash for extracting the prop. There is no use-case where Form Saver handles and array of paths. Idea is set(object, 'a[0].b.c', value); Now one caveat is that set/get path can be written like:
```
['a','0','b','c']
```
But that is just the same as joining the strings

2021-12-17 16:47 UTC, rmcarias commented on src/components/FormSaver/FormSaver.types.ts
> +export interface FormDataObjectType<FormDataType = PrimitiveTypes | Array<PrimitiveTypes>> {
I tried this and there were some TS errors for certain use-cases. Please check them all again.

2021-12-17 19:37 UTC, BrandonDenham reviewed
going to let Rolando take this one.

2021-12-20 12:47 UTC, matiasmarquez commented on src/components/FormSaver/FormSaver.types.ts
> +export type SetterFuncPath = (path: string | string[] | React.SyntheticEvent, value?: any) => void;
Okay, got it I miss understood it. So we have a couple of ways to prevent the `any` casting but I don't know if they are correct. 

One way to go is to cast the property to `SetterFunc` so it can accept any as a value. But the problem is that in Maven we don't have that type because is not exported. Remember that `value` is a `string[]`

![image](https://user-images.githubusercontent.com/31554111/146768882-55ba4604-9e53-4d84-bdc6-25949c7df172.png)

Another way to accomplish this is to use the `nested` property instead: 

![image](https://user-images.githubusercontent.com/31554111/146769153-4e4eba51-3c06-49bc-9f41-ef6b20052a4d.png)

Maybe we will need to see this together. Maybe it isn't so bad to cast in this case to any but I don't know.

2021-12-20 13:04 UTC, matiasmarquez commented on src/components/FormSaver/FormSaver.types.ts
> +export interface FormDataObjectType<FormDataType = PrimitiveTypes | Array<PrimitiveTypes>> {
I was able to test this on TC with the stories of form saver and there is not any TS errors. I tried to test it out on Maven but there is still the problem with the types for the imports.

2021-12-20 18:38 UTC, rmcarias commented on src/components/FormSaver/FormSaver.types.ts
> +export type SetterFuncPath = (path: string | string[] | React.SyntheticEvent, value?: any) => void;
I am ok with either method. We need to fix the SetterFunc type to be explicit to non-nested types in TC

2021-12-20 18:41 UTC, rmcarias commented on src/components/FormSaver/FormSaver.types.ts
> +export interface FormDataObjectType<FormDataType = PrimitiveTypes | Array<PrimitiveTypes>> {
FormDataObjectType | FormDataObjectType<FormDataValueType>

2021-12-20 19:05 UTC, rmcarias approved these changes

2021-12-20 19:05 UTC, merged