saga-12.1078/dsnext-single-roboto-font
Trova-Trip/trova-components pull request #205
Opened 2022-01-10 15:50 UTC by matiasmarquez

Grouped all type fonts in one to just use weights.

2022-01-17 18:14 UTC, rmcarias requested changes

2022-01-17 18:14 UTC, rmcarias commented on src/components/GlobalStyles/GlobalStyles.tsx
> +                    font-weight: ${Fonts.fontWeights.bold};
Almost there I think. The idea was to import only the RobotoRegular font and just change the font-weights appropriately. I think that is what they do when you ask for it via CDN. You ask for Roboto only and the various weights.
That said, if this works well, then we can keep it as such. As long as it's clear to not use the other Font types

2022-01-17 19:10 UTC, matiasmarquez commented on src/components/GlobalStyles/GlobalStyles.tsx
> +                    font-weight: ${Fonts.fontWeights.bold};
If you use only RobotoRegular the other weights will not work. You need to have each file for each weight. You can check how they do here:

https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap

If you see they use differents links for each weight:

- Regular: https://fonts.gstatic.com/s/roboto/v29/KFOmCnqEu92Fr1Mu72xKOzY.woff2
- Medium: https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmEU9fCRc4EsA.woff2
- Bold: https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmWUlfABc4EsA.woff2

They are 3 differents files like I'm doing.

2022-01-18 19:45 UTC, rmcarias approved these changes

2022-01-18 19:45 UTC, merged