saga-12.1082/refactor-fat-component
Trova-Trip/trova-components pull request #206
Opened 2022-01-11 21:09 UTC by matiasmarquez

Major refactor to our FATTY component and fix to use the theme as a prop on `styled` and `css` of Emotion.

**NOTE**: this PR is on **draft** because we can't merge it until this PR https://github.com/Trova-Trip/trova-maven/pull/2018 is merged and I do the implementation and adaptations of this refactor.

2022-01-12 07:26 UTC, BrandonDenham approved these changes

2022-01-13 02:32 UTC, rmcarias requested changes
Very few comments. Really good work Mati! Love where this is going :-)

2022-01-13 02:32 UTC, rmcarias commented on src/components/StickyContentLayout/StickyContentLayout.tsx
> +    }, []);
This has one drawback which is why I think CSS Media watch was needed. It will not be responsive. isMobile will only be true if I start off as mobile. But if I resize my browser, the effect wont run again. 
I mean, I guess we can argue that you either land on mobile or you land on desktop. Usually, you don't start on Desktop and start resizing to a mobile width. However, if it can easily be supported, I say why not. Remember also ResizeObserver and window.matchMedia. Take a look.

2022-01-13 16:52 UTC, rmcarias requested changes

2022-01-13 16:52 UTC, rmcarias commented on src/components/StickyContentLayout/StickyContentLayout.tsx
> +        const isMobile = window.innerWidth <= theme.breakpoints.md;
This logic should probably be encapsulated in a way that all components can tap into it to determine if we are on a mobile device. I thought there was a method already (I think MUI had one)

2022-01-14 15:23 UTC, matiasmarquez commented on src/components/StickyBox/StickyBox.styles.tsx
> +    ${props => isNumber(props.offsetTop) && `bottom: ${props.offsetBottom}px`};
:)

2022-01-14 15:24 UTC, matiasmarquez commented on src/components/StickyContentLayout/Content.tsx
> +    const { children, reversed } = props;
It's related to the `reversed` prop. It means that it can show the mainContent on the left or right

2022-01-14 15:48 UTC, matiasmarquez commented on src/components/StickyContentLayout/StickyContentLayout.tsx
> + * @param reversed - boolean, swaps sideContent to other side
I like the idea. Replace done.

2022-01-14 16:36 UTC, matiasmarquez commented on src/components/StickyContentLayout/Content.tsx
> +    const { children, reversed } = props;
Now it's called `ContentWithAlign` because the change requested to the `reversed` prop below.

2022-01-14 16:48 UTC, matiasmarquez commented on src/components/StickyContentLayout/StickyContentLayout.tsx
> +    }, []);
I think it's not worth add a listener here. If you think it will be only for testing purpose because the problem that we are fixing with that hook applies only for mobile. A normal user won't resize the browser to use the app it's like you said they land on mobile or desktop.

And in terms of performance it's going to be minimal whether we add the listener or not, I agree, but it is something.

2022-01-14 17:11 UTC, matiasmarquez commented on src/components/StickyContentLayout/StickyContentLayout.tsx
> +        const isMobile = window.innerWidth <= theme.breakpoints.md;
Yep, I forgot it. We have a `react-device-detect` dependency on TC that we can use.

2022-01-17 00:00 UTC, rmcarias commented on src/components/StickyContentLayout/StickyContentLayout.tsx
> +    }, []);
Got it and agree. I would, however, still like this mobile logic to be reusable (in a hook)

2022-01-17 00:06 UTC, rmcarias requested changes
coming along good

2022-01-17 00:06 UTC, rmcarias commented on src/components/StickyContentLayout/Content.tsx
>  export const ContentWithStickyContent = forwardRef<
why not just call this StickContentLayout? I am not sure I like the name 'ContentWithStickyContent' it's almost redundant to have Content twice. 
This Comp is technically a Layout comp with behaviour.

2022-01-17 00:06 UTC, rmcarias commented on src/components/StickyContentLayout/Content.tsx
> +        <StyledContentWithStickyContent align={align}>
why do you need the `align` on both comps?
Also, it's usually good to be explicit, I think, on the alignment type if it only supports left and right.. 
`xAlign = 'l' | 'r'`

2022-01-17 12:59 UTC, matiasmarquez commented on src/components/StickyContentLayout/Content.tsx
>  export const ContentWithStickyContent = forwardRef<
Yes, you are right. But I think just `StickContent` is fine because if we call it `StickContentLayout` it will be the very similar to the main component which is called `StickyContentLayout` and it will be confusing.

2022-01-17 13:30 UTC, matiasmarquez commented on src/components/StickyContentLayout/Content.tsx
> +        <StyledContentWithStickyContent align={align}>
Rename prop `align` to `xAlign`.

They both need the prop because they change their style according to the `xAlign` value.

2022-01-17 17:50 UTC, rmcarias requested changes
The interfaces seem a bit off

2022-01-17 17:50 UTC, rmcarias commented on src/components/StickyContentLayout/Content.tsx
> +export const StickyLayoutContent = forwardRef<
I see. It's because all of it is in the same folder as well. That's fine. 
Let's change it to StickyContent then... One is the Layout, and one if the content.
Also rename the file 'Content' -> 'StickyContent'

2022-01-17 17:50 UTC, rmcarias commented on src/components/StickyContentLayout/StickyContentLayout.styles.tsx
> +import { ContentXAlignment } from './StickyContentLayout.types';
Be consistent in your types. These are literally the same. Also, because you have all the component files in the same directory, it's sufficient to just declare all your types in the file `StickContentLayout.types'. 
I am not keen of having these two types of the exact thing

2022-01-17 17:50 UTC, rmcarias commented on src/components/StickyContentLayout/Content.types.ts
> +    xAlign?: ContentXAlignment;
You don't need this extra interface I think. Especially since you have an import that already says you have content with alignment. 
Generally, I don't like calling an interface a name with a specific prop. If tomorrow, we remove the alignment prop, we are stuck with an interface that explicitly calls it out.
See what better techniques of TS you can use to leverage this composition better.

2022-01-17 18:49 UTC, matiasmarquez commented on src/components/StickyContentLayout/Content.tsx
> +export const StickyLayoutContent = forwardRef<
Done

2022-01-17 18:58 UTC, matiasmarquez commented on src/components/StickyContentLayout/StickyContentLayout.styles.tsx
> +import { ContentXAlignment } from './StickyContentLayout.types';
Moved to `StickyContentLayout.types.ts` and removed extra type.

2022-01-17 18:59 UTC, matiasmarquez commented on src/components/StickyContentLayout/Content.types.ts
> +    xAlign?: ContentXAlignment;
Now I created a specific interface on `StickyContentLayout.styles.ts` which uses the `Pick` from Typescript.

2022-01-19 06:20 UTC, rmcarias approved these changes

2022-01-19 18:10 UTC, merged