added loading indicator without svg
Trova-Trip/trova-components pull request #68
Opened 2021-05-04 20:41 UTC by juligobbi-fluxit

2021-05-05 00:23 UTC, mqtik commented
Added SVG component with the following props:
   ```
 size?: number;
    color?: string;
    speed?: number,
    overrideIterator?: string,
    utterance?: number,
    begin?: number,
    duration?: number,
    iterations?: number
```

It's working in storybook with examples. The animations can be configurable, and if needed, overridable.

2021-05-05 06:40 UTC, BrandonDenham requested changes

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/index.ts
> +import { loadingSize } from './loadingSize';
This component shoul dbe named "Loader" not "Loading"

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/loading.tsx
> +    overrideIterator = '0;1;1;0;',
none of these (except className) should be props, they can all be implementation details, size and color should be the only things that need to be customized

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/loading.tsx
> +    size = 240,
We should export an Enum for the sizes, rather than have an open number, we should pick a select set of sizes and have them use that.

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/loading.tsx
> +    const createMarkup = () => {
let's move createMarkup outside of the component definition, and  pass it the parameters that it needs (which now aren't many since we are removing most of the props

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/loading.tsx
> +        function makeBreakpoints() {
same here, rather than define functions inside functions, better to define them separately and use them with parameters if you need it

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/loading.types.ts
> +import { SimpleComponent } from '../../shared/interfaces/SimpleComponent.types';
remember, everything will be changed to Loader

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/loading.styles.tsx
> +      -webkit-mask: url(${iconLoading});
so these are a lot of webkit specific styles? what about other browsers? Firefox? also, typically we dont need any browser specific prefixing.  emotion does "autoprefixing" by default

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/loading.tsx
> +    size = 240,
i think that is the "LoaderSize" enum?

2021-05-05 06:40 UTC, BrandonDenham commented on src/components/loading/loading.tsx
> +    overrideIterator = '0;1;1;0;',
(and className)

2021-05-05 18:18 UTC, mqtik commented on src/components/loading/loading.tsx
> +    overrideIterator = '0;1;1;0;',
Brandon, I'm gonna leave those props there for the time being. I think it's wise that we leave them there, and we edit them internally on trova-components when exporting.

I understand only color, size and className should be public props.

2021-05-05 18:18 UTC, mqtik commented on src/components/loading/loading.tsx
> +    size = 240,
This is outdated.

2021-05-05 18:24 UTC, mqtik commented on src/components/loading/loading.tsx
> +    const createMarkup = () => {
I did move it, preserving the props.

2021-05-05 18:28 UTC, mqtik commented on src/components/loading/loading.styles.tsx
> +      -webkit-mask: url(${iconLoading});
If it was up to me, I'd remove them (theyare not needed).

I'm not sure, so I'll leave Julieta to remove these styles if she wants to.

2021-05-05 18:39 UTC, mqtik commented
Juli, I'm not sure how'd you handle styles.
I think they're not needed, but I could be wrong.

2021-05-05 20:42 UTC, mqtik commented on src/components/loader/loader.styles.tsx
> +      ${size === loaderSize.Sm && `width: 2rem; height: 2rem;`}
We should get rid of these styles. 
Mask is now useless, and the size it's already handled within the component itself.

2021-05-05 20:42 UTC, mqtik commented on src/shared/images/icons/loading.svg
> +<?xml version="1.0" encoding="UTF-8"?>
I think we could remove this file as well.

2021-05-05 20:42 UTC, mqtik commented on src/components/loader/loaderSize.tsx
> +export enum loaderSize {
You can now edit here the sizes, Juli.

2021-05-05 20:42 UTC, mqtik commented on src/components/loader/loader.types.ts
> +export default interface LoaderProps extends SimpleComponent{
Since these props will not be public, I think we could safely remove it. 

Props can still be passed internally to tune the animation.

2021-05-05 20:42 UTC, mqtik commented on src/components/loader/loader.stories.tsx
> +// Should I leave this commented?
You can remove this commented code when you're done.
I left it there so you can see how it can be customizable.

2021-05-05 22:45 UTC, mqtik commented
I think it's looking good.

Let's get Brandon here so he can review it.

2021-05-05 22:49 UTC, juligobbi-fluxit commented on src/components/loading/loading.styles.tsx
> +      -webkit-mask: url(${iconLoading});
We removed them, we no longer use them

2021-05-06 07:10 UTC, BrandonDenham requested changes

2021-05-06 07:10 UTC, BrandonDenham commented on src/components/loader/loader.types.ts
> +export default interface LoaderProps extends SimpleComponent{
this doesn't seem to have typescript executed against it

2021-05-06 07:10 UTC, BrandonDenham commented on src/components/loader/loader.tsx
> +    overrideIterator = '0;1;1;0;'
these can NOT be here in the component that gets exported.  I do not want these available. 

It's very simple to just wrap this in a component that doesn't expose the props.    a secret api is not something we will support in trova-components

2021-05-06 14:32 UTC, mqtik commented on src/components/loading/loading.stories.tsx
> +import { loadingSize } from '.';
I didn´t write that, but suprisingly everything works.

I´m just gonna change it anyway.

2021-05-07 16:19 UTC, juligobbi-fluxit commented on src/components/loader/loader.types.ts
> +export default interface LoaderProps extends SimpleComponent{
@BrandonDenham what do you mean with that?

2021-05-10 08:03 UTC, BrandonDenham commented on src/components/loader/loader.types.ts
> +export default interface LoaderProps extends SimpleComponent{
sorry i meant prettier

2021-05-11 07:16 UTC, BrandonDenham commented
where are we with this PR?

2021-05-13 21:17 UTC, merged