added UserMenu component - initial commit with the basic layout
Trova-Trip/trova-components pull request #70
Opened 2021-05-06 22:55 UTC by juligobbi-fluxit

2021-05-07 06:48 UTC, BrandonDenham requested changes

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserMenu.tsx
> +const UserMenu: React.FC<UserMenuProps> = ({
This should not be "UserMenu" it should just be Menu.  It needs to be able to attach itself to any element.  

This is what we discussed in standup, that it would take a "menuTarget" as a prop and that menuTarget should be a ref https://reactjs.org/docs/refs-and-the-dom.html.  

We want this to be flexible enough to attach to any react element.   This component should attach click handlers to the ref and hover /click styles to the ref that is passed and the positioning should be relative to that element.  

@eringuelet please connect with Julieta on this as this will fundamentally change the component.

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserMenu.tsx
> +            <div css={userMenuDropdown}>{openMenu ? children : null}</div>
we don't have empty div on the page with empty content, we just don't display the div at all

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserMenu.tsx
> +            <button css={userMenuButton} onClick={() => toggle()}>
you dont need () => toggle();  that defeats the point of useCallback

you would just have onClick={toggle}

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserMenu.tsx
> +const UserMenu: React.FC<UserMenuProps> = ({
we don't need/want any profile image stuff at all

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserItem.styles.tsx
> +        background-color: #eff1f7;
colors should be sourced from the theme, never hard coded

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserItem.styles.tsx
> +    font-size: 14px;
i believe font-sizes should be in the theme as well

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserItem.tsx
> +/** @jsx jsx */
Should be called MenuItem, not UserItem

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserItem.tsx
> +    title,
this should be the children, not title

2021-05-07 06:48 UTC, BrandonDenham commented on src/components/userMenu/UserItem.tsx
> +    const itemClicked = useCallback(
call this handleItemClicked

2021-05-12 15:07 UTC, eringuelet approved these changes

2021-05-13 01:50 UTC, BrandonDenham requested changes

2021-05-13 01:50 UTC, BrandonDenham commented on src/components/menu/Menu.stories.tsx
> +            <Menu open={openMenu} title="User" referenceRef={parentRef}>
can we call this targetRef, not refereneRef

2021-05-13 01:50 UTC, BrandonDenham commented on src/components/menu/Menu.tsx
> +    referenceRef = {},
hmm, i don't think there is a default.  This is required

2021-05-13 01:50 UTC, BrandonDenham commented on src/components/menu/Menu.types.ts
> +    open?: boolean;
so if this is optional, it means you have to handle it with internal state and let them open and close it internally.  That's not what's happening here.  Although i think it should be.

2021-05-13 01:50 UTC, BrandonDenham commented on src/components/menu/Menu.tsx
> +            {open && children}
open should be around the entire thing, otherwise we have empty divs left around

2021-05-13 01:50 UTC, BrandonDenham commented on src/components/menu/Menu.tsx
> +        placement: `bottom-start`,
we should let them have a prop to control the placement, either left/right i think

2021-05-13 01:50 UTC, BrandonDenham commented on src/components/menu/Menu.types.ts
> +    onToggle?: (arg0: boolean) => boolean;
you aren't using onToggle in the implementation.  so this is useless?

2021-05-13 01:50 UTC, BrandonDenham commented on src/components/menu/Menu.types.ts
> +    children: object;
object? it's a react.node right?

2021-05-14 06:54 UTC, BrandonDenham approved these changes
added some comments, but approved

2021-05-14 06:54 UTC, BrandonDenham commented on src/components/menu/Menu.tsx
> +    placement = `bottom-start`,
this maybe should be an enum that you map to the values you want to support.  Otherwise there is no where this is documented

2021-05-14 06:54 UTC, BrandonDenham commented on src/components/menu/Menu.tsx
> +    placement = `bottom-start`,
can use a string enum: https://www.typescriptlang.org/docs/handbook/enums.html#string-enums

2021-05-14 06:54 UTC, BrandonDenham commented on src/components/menu/Menu.tsx
> +            targetRef.current.onclick = () => setOpen(!open);
you might also add the cursor: pointer style so that it looks clickable

2021-05-14 06:54 UTC, BrandonDenham commented on src/components/menu/Menu.tsx
> +            targetRef.current.onclick = () => setOpen(!open);
and remove it below

2021-05-14 14:16 UTC, eringuelet commented on src/components/menu/Menu.tsx
> +    placement = `bottom-start`,
The `placement` prop is taking the value from the same place as the library does; it's an internal Popper object where contains the different accepted values. Should I create a new object containing a subset of them?

2021-05-14 14:39 UTC, merged