New component: Badge
Trova-Trip/trova-components pull request #82
Opened 2021-05-20 21:59 UTC by mqtik

2021-05-21 02:23 UTC, BrandonDenham commented on src/components/badge/badge.test.tsx
> +import userEvent from '@testing-library/user-event';
seems to be alot of unused imports

2021-05-21 02:39 UTC, BrandonDenham requested changes

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/badge/badge.test.tsx
> +describe('Badge', () => {
so should actually write some of the tests

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/badge/badge.styles.tsx
> +export const mainContainer = (backgroundColor: string, borderRadius: number) => css`
lets name this badgeContainer

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/badge/badge.styles.tsx
> +export const detailSpan = (color: string,fontSize: number) => css`
lets call it badgeText

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/badge/badge.tsx
> +/** @jsx jsx */
fileName  should match default export (so be capitalized)

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/loader/_private/componentLoader.tsx
> +const Loader: React.FC<LoaderProps> = (props: any) => {
props should be LoaderPros, not any

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/badge/badge.types.ts
> +    color?: string;
the props should be the props from the approved design:  https://trovatrip.slite.com/api/s/note/Wsdf6nLehQSJUhhoXb2TaK/Badge  

label should be text and it should be required.  

borderRadius and fontSize should NOT be exposed, please remove

onClick and color are OK (so add them to the design doc), but color should be an enum of our colors, onClick should be a function, not any (NEVER any) 

if it's not listed in the api in the design doc, it shouldn't be here.   These things shouldn't come up in code review but on design doc comments where you ping the members of the team.

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/badge/badge.tsx
> +    const theme = useTheme();
unused?

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/badge/badge.tsx
> +    const handleBadge = useCallback(
handleBadgeClick

2021-05-21 02:39 UTC, BrandonDenham commented on src/components/badge/badge.tsx
> +import ComponentFooter from '../__private/componentFooter';
unused?

2021-05-28 07:36 UTC, BrandonDenham approved these changes
some comments, please address then this is good to merge

2021-05-28 07:36 UTC, BrandonDenham commented on src/components/badge/badge.stories.tsx
> +        borderRadius={50}
can delete the non-used props

2021-05-28 07:36 UTC, BrandonDenham commented on src/components/badge/badge.tsx
> + * @param  props.backgroundSize - backgroundSize
these should be accurate

2021-05-28 07:36 UTC, BrandonDenham commented on src/components/badge/badge.types.ts
> +    borderRadius?: number;
delete the nonused props from here please

2021-05-28 07:36 UTC, BrandonDenham commented on src/components/badge/badge.types.ts
> +    fontSize?: number;
delete

2021-05-28 07:36 UTC, BrandonDenham commented on src/components/badge/badge.types.ts
> +    label?: string;
this should be required i think

2021-06-03 20:52 UTC, parrajulian commented on src/components/badge/badge.stories.tsx
> +        borderRadius={50}
done

2021-06-03 20:52 UTC, parrajulian commented on src/components/badge/badge.tsx
> + * @param  props.backgroundSize - backgroundSize
on sync with the spec

2021-06-03 20:52 UTC, parrajulian commented on src/components/badge/badge.tsx
> + * @param  props.backgroundSize - backgroundSize
modified

2021-06-03 20:52 UTC, parrajulian commented on src/components/badge/badge.types.ts
> +    borderRadius?: number;
deleted

2021-06-03 20:53 UTC, parrajulian commented on src/components/badge/badge.types.ts
> +    fontSize?: number;
done

2021-06-03 20:53 UTC, parrajulian commented on src/components/badge/badge.types.ts
> +    label?: string;
label changed to text and is now required

2021-06-03 20:53 UTC, merged