Currency Input component
Trova-Trip/trova-components pull request #88
Opened 2021-06-01 15:07 UTC by juligobbi-fluxit

It is created the Currency Input component. It is pending to take the functionality of the input

2021-06-02 08:11 UTC, BrandonDenham requested changes

2021-06-02 08:11 UTC, BrandonDenham commented on src/components/currency/Currency.tsx
> +    const currency = 'USD';
we need a currencyPosition prop that defaults to left since some currencies show up on the right of an input

2021-06-02 08:11 UTC, BrandonDenham commented on src/components/currency/Currency.tsx
> +    const currency = 'USD';
we also need a decimalPlaces prop that defaults to 0.  currencies will need to have decimals in some cases.

2021-06-02 08:11 UTC, BrandonDenham commented on src/components/currency/Currency.tsx
> +                    onChange={e => handleChange(e, parseInt(e.target.value))}
you shouldnt have any logic inline of the onChange prop, should move any parsing to the handleChange function itself

Also, you cant use "parseInt" since we need to support decimals

something like:

Number(Number.parseFloat(value).toFixed(props.decimalPlaces));
or something

2021-06-02 08:11 UTC, BrandonDenham commented on src/components/currency/Currency.tsx
> +            {error && Array.isArray(error) && (
what if array is empty

2021-06-02 08:11 UTC, BrandonDenham commented on src/components/currency/Currency.tsx
> +            {error && Array.isArray(error) && (
basically should calculate the errortext outside of the return then inside the return can be simple:

{errorText && <span css={errorSpan(theme)}>{errorText}</span>}

2021-06-03 00:33 UTC, juligobbi-fluxit commented
**Regarding requested changes, in the following commit:**

**is Solved:**
- Was created a "CurrencyProps" interface that extends "FieldProps"
- Added currencyType as a prop
- Added currencyPosition as a prop
- Added decimalPlaces as a prop that defaults to 0.
- Take outside the logic inline of the onChange prop
- Error function:
Take outside the error function
Extended the function (empty, single, multiple)

**Also added 2 variants more:**
- Added size as a prop and with an example in the stories. To use the extra small size in tables.
- Added position as a prop and with an example in the stories. To use the position left or right for the type of currency.


**is Pending:**
- Need to support decimals. Example:
	Number(Number.parseFloat(value).toFixed(props.decimalPlaces));

2021-06-03 00:35 UTC, juligobbi-fluxit commented on src/components/currency/Currency.tsx
> +    const currency = 'USD';
Were solved the three of them

2021-06-03 00:36 UTC, juligobbi-fluxit commented on src/components/currency/Currency.tsx
> +const Currency: React.FC<FieldProps<number>> = ({
Was solved

2021-06-03 00:40 UTC, juligobbi-fluxit commented on src/components/currency/Currency.tsx
> +                    onChange={e => handleChange(e, parseInt(e.target.value))}
I took the logic inline of the onChange prop out. The decimal is pending.

2021-06-03 00:42 UTC, juligobbi-fluxit commented on src/components/currency/Currency.tsx
> +            {error && Array.isArray(error) && (
Was solved

2021-06-03 19:02 UTC, BrandonDenham approved these changes
nice job!

2021-06-03 19:23 UTC, merged