TimePicker input fixes and improvements
Trova-Trip/trova-components pull request #90
Opened 2021-06-04 13:43 UTC by cristian-seoane

Added a custom "HH:mm" masked input, and auto-fill feature to TimePicker component, in order to fix input behavior.

*Added "react-input-mask": "^2.0.4" lightweight  library that provides auto-fill feature (very useful for masked inputs)
*Added  types for react-input-mask library  "@types/react-input-mask": "^3.0.0"

**This PR solves #1151  issues from trova-maven project

2021-06-08 05:28 UTC, BrandonDenham requested changes

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/DateTime.types.ts
> +    props: any,
we never use any, props must be defined

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/DateTime.types.ts
> +    props: any,
as an actual description

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/DateTime.types.ts
> +    closeCalendar: Function,
We need to be more descriptive, what are the parameters? what is the return value of these functions

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/TimePicker.tsx
> +
dont define this as a function inside of the component, that is bad performance and is pointless.  In fact, "renderInput" shouldn't be a function, it should be a separate react component written in a __private directory.  

RenderInput is not a good name, I believe it should be InputMaskWrapper to tell what it actually does

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/TimePicker.tsx
> +        const regEx = /^(2[0-3]|[0-1]?[\d]):[0-5][\d]$/;
we dont want to define constants inside of functions if they never changes, because then they are pointlessly re-defined on every render, should move this up to the module level

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/TimePicker.tsx
> +        const handleChange = (e: SyntheticEvent) => {
no abbreviations, please use event not e

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/TimePicker.tsx
> +        };
we dont use any, also we can just pass in openCalendar

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/TimePicker.tsx
> +
and again, it should be a function, but a react component with props

2021-06-08 05:28 UTC, BrandonDenham commented on src/components/TrovaDateTime/DateTime.types.ts
> +export type RenderInput = (
after reading, this type won't exist, there will be an interface "InputMaskProps" and it wont be a function, it will be a Component

2021-06-09 18:18 UTC, cristian-seoane commented on src/components/TrovaDateTime/DateTime.types.ts
> +    props: any,
Got it!

2021-06-09 18:19 UTC, cristian-seoane commented on src/components/TrovaDateTime/DateTime.types.ts
> +    closeCalendar: Function,
Got it!

2021-06-09 18:19 UTC, cristian-seoane commented on src/components/TrovaDateTime/TimePicker.tsx
> +
Got it!

2021-06-09 18:19 UTC, cristian-seoane commented on src/components/TrovaDateTime/TimePicker.tsx
> +        const regEx = /^(2[0-3]|[0-1]?[\d]):[0-5][\d]$/;
Got it!

2021-06-09 18:19 UTC, cristian-seoane commented on src/components/TrovaDateTime/TimePicker.tsx
> +        };
Got it!

2021-06-09 18:20 UTC, cristian-seoane commented on src/components/TrovaDateTime/TimePicker.tsx
> +        const handleChange = (e: SyntheticEvent) => {
Got it!

2021-06-11 18:06 UTC, merged