Responsive styles for navigation layouts
Trova-Trip/trova-components pull request #93
Opened 2021-06-11 13:24 UTC by juligobbi-fluxit

Responsive styles for mainContent, mainNavigation, mainNavigationIte and Sidebar. Removing grid system library and replacing for material-ui. Added breakpoints.

2021-06-13 07:39 UTC, BrandonDenham requested changes

2021-06-13 07:39 UTC, BrandonDenham commented on src/components/mainNavigation/MainNavigation.styles.tsx
> +    }
an empty query?

2021-06-13 07:39 UTC, BrandonDenham commented on src/components/mainNavigation/MainNavigationItem.styles.tsx
> +export const mainNavigationItemArrow = css``;
empty styles?

2021-06-15 20:32 UTC, juligobbi-fluxit commented on src/components/mainNavigation/MainNavigation.styles.tsx
> +    }
Sorry, I will correct it in the next commit. It was left like this because of the last changes I made, I did not realize about it

2021-06-15 20:32 UTC, juligobbi-fluxit commented on src/components/mainNavigation/MainNavigationItem.styles.tsx
> +export const mainNavigationItemArrow = css``;
ídem

2021-06-16 15:54 UTC, BrandonDenham approved these changes

2021-06-16 18:29 UTC, merged